import React, { useLayoutEffect } from 'react'
import { FlatList, Button, Alert, View, Text } from 'react-native'
import { useSelector, useDispatch } from 'react-redux'
import { StackNavigationProp } from '@react-navigation/stack'
import { CompositeNavigationProp } from '@react-navigation/native'
import { DrawerNavigationProp } from '@react-navigation/drawer'

import CustomHeaderButton from '../../components/UI/CustomHeaderButton'
import ProductItem from '../../components/shop/ProductItem'
import Colors from '../../constants/Colors'
import * as productActions from '../../store/actions/products'
import { RootState } from '../shop/index.d'
import {
  AdminStackParamList,
  ShopDrawerParamList,
} from '../../navigation/paramList'

type UserProductsScreenNavigationProp = CompositeNavigationProp<
  StackNavigationProp<AdminStackParamList, 'UserProductsScreen'>,
  DrawerNavigationProp<ShopDrawerParamList, 'Admin'>,
>

type Props = {
  navigation: UserProductsScreenNavigationProp,
}

const UserProductsScreen = ({ navigation }: Props) => {
  const userProducts = useSelector(
    (state: RootState) => state.products.userProducts,
  )
  const dispatch = useDispatch()

  useLayoutEffect(() => {
    navigation.setOptions({
      headerLeft: () => (
        <CustomHeaderButton
          iconName='navicon'
          onPress={() => {
            navigation.openDrawer()
          }}
        />
      ),
    })
  }, [navigation])
  useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <CustomHeaderButton
          iconName='plus'
          onPress={() => {
            navigation.navigate('EditProductsScreen', { productId: '' }) // productId is generated by firebase when creating new product
          }}
        />
      ),
    })
  }, [navigation])

  const deleteHandler = (id: string) => {
    Alert.alert('Are you sure?', 'Do you really want to delte this item?', [
      { text: 'No', style: 'default' },
      {
        text: 'Yes',
        style: 'destructive',
        onPress: () => {
          dispatch(productActions.deleteProduct(id))
        },
      },
    ])
  }

  const editProductHandler = (id: string) => {
    navigation.navigate('EditProductsScreen', { productId: id })
  }

  if (!userProducts.length) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>No products found. Maybe you should create some</Text>
      </View>
    )
  }

  return (
    <FlatList
      data={userProducts}
      keyExtractor={(item) => item.id}
      contentContainerStyle={{
        alignItems: 'center',
      }}
      initialNumToRender={6}
      numColumns={2}
      renderItem={(itemData) => (
        <ProductItem
          image={itemData.item.imageUrl}
          title={itemData.item.title}
          price={itemData.item.price}
        >
          <Button
            color={Colors.primary}
            title='Edit'
            onPress={() => {
              editProductHandler(itemData.item.id)
            }}
          />
          <Button
            color={Colors.primary}
            title='Delete'
            onPress={() => deleteHandler(itemData.item.id)}
          />
        </ProductItem>
      )}
    />
  )
}

export default UserProductsScreen
